import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "../components/Header";
import { MenuProvider } from "@/context";
import customizedFetch from "@/ultis/fetch";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await customizedFetch("/en/config");
  const menu = response.menu;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MenuProvider initialData={{
          ...menu,
          gamesOfTheMonth: response.gamesOfTheMonth
        }}>
          <Header />
          {children}
        </MenuProvider>
      </body>
    </html>
  );
}
